In [1]:
import numpy as np
import sys as sys

# Broadcasting and Vectorized Operations 

In [2]:
a = np.arange(8)

so does arange gives the array an index?

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17])

In [5]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [6]:
a += 100 ## this will continue to add each time you run program as an individual line, don't make that mistake

In [7]:
l = [0, 1, 2, 3]

In [8]:
[i * 10 for i in l] ## this is what np.arange() does

[0, 10, 20, 30]

In [12]:
a = np.arange(4)

In [13]:
a

array([0, 1, 2, 3])

In [14]:
b = np.array([10, 10, 10, 10])

In [15]:
a + b

array([10, 11, 12, 13])

In [16]:
a * b 

array([ 0, 10, 20, 30])

# Boolean Arrays




In [17]:
a = np.array(4)

In [18]:
new_matrix = np.array([[1, 2, 3], 
                       [4, 5, 6], 
                       [7, 8, 9]
                       ])


Below we changed the last element in each dimension to 20

In [19]:
new_matrix[:, 2] = 20
print(new_matrix[:, 2])

[20 20 20]


# Initializing Different Types of Arrays

In [20]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [21]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other number
np.full((2,2), 99, dtype=float32)

NameError: name 'float32' is not defined

In [23]:
new_matrix

array([[ 1,  2, 20],
       [ 4,  5, 20],
       [ 7,  8, 20]])

In [24]:
np.full_like(new_matrix, 4) # straight up changes new_matrix to a different new_matrix


array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [25]:
np.random.rand(4,2) # random decimal numbers in a certain shape

array([[0.99871009, 0.64096835],
       [0.65978908, 0.36719981],
       [0.36356868, 0.69689271],
       [0.39158505, 0.14219862]])

In [26]:
np.random.random_sample(new_matrix.shape) # random decimal numbers matching a current variables shape

array([[0.33832513, 0.19098601, 0.65712417],
       [0.21500753, 0.84295903, 0.23675836],
       [0.96929118, 0.36552924, 0.90820396]])

In [27]:
np.random.randint(7) # random Integer Values

0

In [28]:
np.random.randint(1, 7, size=(3,3)) #random ints in 3 by 3 all below 7

array([[1, 2, 1],
       [3, 3, 3],
       [3, 5, 5]])

In [29]:
arr = np.array([[1,2,3]]) # repeating in 1 dimension
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [30]:
arr2 = np.array([[1,2,3]]) # repeating in multi dimension, be wary of the number of brackets used,
r2 = np.repeat(arr2, 3, axis=0) # if only 1 bracket used it will throw an error
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Initialize Array Problem


# Boolean Arrays
Bools are Similar to Vectorized Arrays in NumPy

In [36]:
a = np.arange(4)
print(a)


[0 1 2 3]


In [38]:
# Array Selection with Bool
a[[True, False, False, True]]

array([0, 3])

In [39]:
a[True, False, False, True] # super interesting output

array([], shape=(0, 4), dtype=int32)

In [40]:
a >= 2

array([False, False,  True,  True])

In [41]:
a[a >= 2] # helps us to filter numeric arrays, query method

array([2, 3])

In [43]:
a.mean()


1.5

In [44]:
a[~(a > a.mean())]

array([0, 1])

In [46]:
a[(a == 0) | (a == 1 )] # comparing with or

array([0, 1])

In [47]:
a[(a <= 2) & (a % 2 == 0)] # comparing with and 

array([0, 2])

In [52]:
A = np.random.randint(100, size=(3, 3))

In [53]:
A

array([[48, 30, 89],
       [18, 79, 28],
       [97, 48,  5]])

In [54]:
A > 30

array([[ True, False,  True],
       [False,  True, False],
       [ True,  True, False]])

In [55]:
A[A > 30]

array([48, 89, 79, 97, 48])

In [56]:
b = np.arange(5)

In [57]:
a <= 3

array([ True,  True,  True,  True])

# Algebra and Size 

In [63]:
c = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]
])

In [64]:
d = np.array([
    [6, 5], 
    [4, 3],
    [2, 1]
])

In [65]:
c.dot(d)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [66]:
c @ d

array([[20, 14],
       [56, 41],
       [92, 68]])

In [67]:
d.T

array([[6, 4, 2],
       [5, 3, 1]])

In [68]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
d.T @ c

array([[36, 48, 60],
       [24, 33, 42]])

# Size of Objects in Memory

In [79]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [80]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [72]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [73]:
np.dtype(float).itemsize

8

# Lists are Even Larger

In [81]:
# A one-element list
sys.getsizeof([1])

64

In [75]:
# An array of one element in NumPy
np.array([1]).nbytes

4

In [82]:
l = list(range(1000))

In [84]:
q = np.arange(1000)

In [87]:
%time np.sum(q ** 2)

CPU times: total: 0 ns
Wall time: 0 ns


332833500

In [88]:
%time sum([x**2 for x in l])

CPU times: total: 0 ns
Wall time: 0 ns


332833500

# Useful NumPy Functions

In [89]:
np.random.random(size=2)

array([0.39193902, 0.7695067 ])

In [90]:
np.random.normal(size=2)

array([-0.01147881, -1.73120705])

https://www.freecodecamp.org/learn/data-analysis-with-python/data-analysis-with-python-course/numpy-algebra-and-size
Above link is video of some useful functions