In [29]:
import numpy as np

# Broadcasting and Vectorized Operations 

In [30]:
a = np.arange(8)

so does arange gives the array an index?

In [31]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17])

In [33]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [34]:
a += 100 ## this will continue to add each time you run program as an individual line, don't make that mistake

In [38]:
l = [0, 1, 2, 3]

In [39]:
[i * 10 for i in l] ## this is what np.arange() does

[0, 10, 20, 30]

In [41]:
a = np.arange(4)

In [42]:
a

array([0, 1, 2, 3])

In [43]:
b = np.array([10, 10, 10, 10])

In [44]:
a + b

array([10, 11, 12, 13])

In [45]:
a * b 

array([ 0, 10, 20, 30])

# Boolean Arrays




In [ ]:
a = np.array(4)

In [46]:
new_matrix = np.array([[1, 2, 3], 
                       [4, 5, 6], 
                       [7, 8, 9]
                       ])


Below we changed the last element in each dimension to 20

In [51]:
new_matrix[:, 2] = 20
print(new_matrix[:, 2])

[20 20 20]


# Initializing Different Types of Arrays

In [52]:
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [54]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
# Any other number
np.full((2,2), 99, dtype=float32)

In [57]:
new_matrix

array([[ 1,  2, 20],
       [ 4,  5, 20],
       [ 7,  8, 20]])

In [58]:
np.full_like(new_matrix, 4) # straight up changes new_matrix to a different new_matrix


array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [60]:
np.random.rand(4,2) # random decimal numbers in a certain shape

array([[0.22155962, 0.73869795],
       [0.48686092, 0.22118083],
       [0.21698722, 0.40436405],
       [0.02799703, 0.16288082]])

In [61]:
np.random.random_sample(new_matrix.shape) # random decimal numbers matching a current variables shape

array([[0.93547351, 0.16269554, 0.39765198],
       [0.11677174, 0.86079398, 0.11976015],
       [0.73472486, 0.83569222, 0.70734788]])

In [62]:
np.random.randint(7) # random Integer Values

5

In [75]:
np.random.randint(1, 7, size=(3,3)) #random ints in 3 by 3 all below 7

array([[2, 5, 4],
       [5, 4, 4],
       [4, 3, 5]])

In [85]:
arr = np.array([[1,2,3]]) # repeating in 1 dimension
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [84]:
arr2 = np.array([[1,2,3]]) # repeating in multi dimension, be wary of the number of brackets used,
r2 = np.repeat(arr2, 3, axis=0) # if only 1 bracket used it will throw an error
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Initialize Array Problem
